[project]
name = "bpodaolo"
version = "0.1.0"
description = "Basic principles of data analytics and optimization for logistics and operations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.0",
    "simpy>=4.1.1",
]
